[set_wazuh_host]
DEST_KEY = MetaData:Host
# This Regex specifically looks for the "name" field and captures everything inside the quotes
REGEX = \"agent\":\{.*?\"name\":\"(?<extracted_host>[^\"]+)\"
FORMAT = host::$1
